package jasper.llvm

import jasper.ast.*
import java.io.File
import java.nio.file.Path

class LlvmBackend {
    fun generate(
        packageName: String?,
        declarations: List<JasDeclaration>,
        outputDir: Path
    ) {
        val irCode = generateIr(declarations)
        val filename = (packageName ?: "output").replace('.', '/')
        val file = outputDir.resolve("$filename.ll").toFile()
        file.parentFile.mkdirs()
        file.writeText(irCode)
    }

    private fun generateIr(declarations: List<JasDeclaration>): String {
        val sb = StringBuilder()
        sb.appendLine("; Generated by Jasper LLVM Backend")
        sb.appendLine("target triple = \"x86_64-pc-windows-msvc\"")
        sb.appendLine()

        // Declare external functions
        sb.appendLine("declare i32 @printf(i8*, ...)")
        sb.appendLine()

        for (decl in declarations) {
            when (decl) {
                is JasFunction -> generateFunction(sb, decl)
                else -> {} // Skip non-functions for now
            }
        }
        return sb.toString()
    }

    private fun generateFunction(sb: StringBuilder, func: JasFunction) {
        val returnType = llvmType(func.returnType)
        val paramTypes = func.parameters.joinToString(", ") { llvmType(it.type) }

        sb.appendLine("define $returnType @${func.name}($paramTypes) {")
        sb.appendLine("  entry:")

        val body = func.body
        if (body != null) {
            generateBlock(sb, body, "  ")
        }

        // Default return
        sb.appendLine("  ret $returnType 0")
        sb.appendLine("}")
        sb.appendLine()
    }

    private fun generateBlock(sb: StringBuilder, block: JasBlock, indent: String) {
        for (stmt in block.statements) {
            when (stmt) {
                is JasReturn -> {
                    val value = stmt.value
                    if (value != null) {
                        sb.appendLine("$indent  ret ${llvmType(value)} ${llvmValue(value)}")
                    }
                }
                else -> {}
            }
        }
    }

    private fun llvmType(type: JasType?): String {
        return when (type) {
            is JasPrimitiveType -> when (type.name) {
                "int32" -> "i32"
                "int64" -> "i64"
                "float32" -> "float"
                "float64" -> "double"
                "bool" -> "i1"
                "byte" -> "i8"
                else -> "i32"
            }
            is JasUnitType -> "void"
            is JasStringType -> "i8*"
            is JasAnyType -> "i8*"
            is JasNamedType -> "i8*"
            else -> "i32"
        }
    }

    private fun llvmType(expr: JasExpression): String = llvmType(inferType(expr))

    private fun llvmValue(expr: JasExpression): String {
        return when (expr) {
            is JasIntLiteral -> expr.value.toString()
            is JasFloatLiteral -> expr.value.toString()
            is JasBoolLiteral -> if (expr.value) "1" else "0"
            is JasNullLiteral -> "null"
            else -> "0"
        }
    }

    private fun inferType(expr: JasExpression): JasType? {
        return when (expr) {
            is JasIntLiteral -> JasPrimitiveType("int32")
            is JasFloatLiteral -> JasPrimitiveType("float32")
            is JasStringLiteral -> JasStringType
            is JasBoolLiteral -> JasPrimitiveType("bool")
            is JasNullLiteral -> JasAnyType
            else -> JasPrimitiveType("int32")
        }
    }
}
